# Generated by Django 3.2 on 2021-06-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='name',
            field=models.CharField(default='森のくまさん', max_length=20, null=True),
        ),
    ]
