# Generated by Django 3.2 on 2021-06-03 06:18

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0008_alter_bbs_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='created_at',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True),
        ),
    ]
