# Generated by Django 3.2 on 2021-06-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0010_alter_bbs_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='ip',
            field=models.CharField(default='192.168.43.21', max_length=50),
        ),
    ]
