# Generated by Django 3.2 on 2021-06-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0011_alter_bbs_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='ip',
            field=models.CharField(default=b'MTkyLjE2OC40My4yMQ==', max_length=50),
        ),
    ]
