# Generated by Django 3.2 on 2021-06-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0014_alter_bbs_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='ip',
            field=models.CharField(default='MT', max_length=50),
        ),
    ]
