# Generated by Django 3.2 on 2021-06-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0017_remove_bbs_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='ip',
            field=models.CharField(max_length=50),
        ),
    ]
